### ISSUE TITLE
Premium/Discount to NAV for all 10 new ETFs

### ISSUE THREAD

**Issue by MajorGeneralHammond** [BitboBTC/Feedback#12]
You have GBTC, was hoping you could get the others. Thank you!

**Comment by JTuwiner** [comment]
We're working on it. Hopefully be live next week.

**Comment by dooberdoober** [comment]
Thats great to hear! Will be looking forward to it! Thanks for a great website info dashboard!

**Comment by JTuwiner** [comment]
Should be up tomorrow, I think. 

We will add price and also price in sats

**Comment by JTuwiner** [comment]
Should have price in USD and price in sats today shortly, premiums later today or tomorrow

As for calcing premiums, it seems best way is to do the ETF price divided by Bitcoin price to calculate the approximate BTC price of each ETF. 

And then calc the ETF premium based on that, right? 

I don't see anywhere online otherwise that states how much BTC each share is 

@dooberdoober @MajorGeneralHammond

**Comment by JTuwiner** [comment]
<img width="473" alt="Screenshot 2024-01-17 at 1 20 41 PM" src="https://github.com/BitboBTC/Feedback/assets/2924924/29a7c8c3-23ed-4969-8f40-af49dffd3938">

not live yet, but prices are up. 

Need to add new section for premiums, and add sat price/equivalent

**Comment by dooberdoober** [comment]
> Should have price in USD and price in sats today shortly, premiums later today or tomorrow
> 
> As for calcing premiums, it seems best way is to do the ETF price divided by Bitcoin price to calculate the approximate BTC price of each ETF.
> 
> And then calc the ETF premium based on that, right?
> 
> I don't see anywhere online otherwise that states how much BTC each share is
> 
> @dooberdoober @MajorGeneralHammond

Yeah. As far as I have seen, there is not yet an easy way to find out how many sats each share is so the math you suggested is what I had in mind.

**Comment by JTuwiner** [comment]
But that would make it that there's no premium. If we're going to use the ETF price to determine equivalent BTC price.

**Comment by JTuwiner** [comment]
prices are live. still figuring out best way to determine premium. With GBTC it was easy because GBTC published exactly how many BTC each share represented.

**Comment by dooberdoober** [comment]
Probably stick with what it is and update as that information becomes available. Its great to see them on the site now, btw!

**Comment by JTuwiner** [comment]
I found the info for IBIT. Working on adding now

For example for IBIT

16,361.6389 BTC they own / 20,080,000 shares = 0.000814822654382 BTC per share

Will need to find the other ones and also monitor if the BTC per share changes with time

**Comment by JTuwiner** [comment]
Any ideas here? @MajorGeneralHammond @dooberdoober 

data from https://www.ishares.com/us/products/333011/ishares-bitcoin-trust

IBIT claims to have 16,361.6389 BTC and 20,080,000 shares

that means each share = 0.000814822654382 BTC

however when I run that math I'm getting an equivalent BTC price of  $29,957.44 which is off

working on adding volume first before I add these premiums, as the premiums seem tricky

**Comment by JTuwiner** [comment]
<img width="476" alt="Screenshot 2024-01-18 at 1 36 25 PM" src="https://github.com/BitboBTC/Feedback/assets/2924924/d54721ba-a3d1-4e50-9d55-4390045bd12e">

volume coming soon

**Comment by dooberdoober** [comment]
Its great to see IBIT have such a great info page. On a less positive note, IBIT shares are already quite different than when you shared that page. 28,720,000 shares as of time of this post. With net assets listed at $698,142,357.

EDIT: Net assets of fund is $698,142,357 but market value of bitcoin they hold is $1,060,712,715.95
*I dont understand this difference.

**Comment by JTuwiner** [comment]
Right, it's going to make it very difficulty to calculate premiums. Unless I can figure out a set BTC per share price

**Comment by dooberdoober** [comment]
Yep. ETF section may take many weeks to get all the info listed.
I see IBIT has discount/premium on the page you shared. Once data starts to show there, can it be used to keep the accurate premium listed on bitbo?

**Comment by dooberdoober** [comment]
Tone Vays has been trying to do this too, as well as another twitter account that he mentions in the linked video. None are  100% accurate. There are multiple different settlement time periods involved with all this, T+0 - T+2 which increases the difficulty in achieving the end goal, quite a bit, at least with how im thinking about it. https://www.youtube.com/watch?v=8lYT1MmVDJM

**Comment by JTuwiner** [comment]
Yeah, I'm probably going to hold off on premiums for now until it becomes more clear. Regardless, it seems like only GBTC has a big premium for now. 

I also just put this page up https://buybitcoinworldwide.com/etf-holdings/

We'll update this every night when the updated holdings come in

And it will also be up on bitbo.io soon

I'll re-open this if any news comes out about us adding premiums.

**Comment by JTuwiner** [comment]
https://twitter.com/BitcoinNewsCom/status/1748401677990842458

here's one showing BTC per share

**Comment by JTuwiner** [comment]
Making progress

Thanks @MajorGeneralHammond https://twitter.com/FieldNas/status/1749074082656649248

Also ARKB has 7565000 shares and 7,565BTC, so that makes it an easy .001 BTC per share

<img width="418" alt="Screenshot 2024-01-21 at 10 47 25 AM" src="https://github.com/BitboBTC/Feedback/assets/2924924/6051b004-e95a-47e3-b8e7-86e5703b4ddc">

**Comment by dooberdoober** [comment]
Looks great! Ill keep an eye out for any of the info still missing

**Comment by dooberdoober** [comment]
BTCW - Wisdomtree

https://www.wisdomtree.com/investments/etfs/crypto/btcw
![Screenshot_20240123_234129](https://github.com/BitboBTC/Feedback/assets/29629527/d449efb7-e751-4039-bbb3-d6c7652fee66)

**Comment by dooberdoober** [comment]
BRRR - Valkyrie

https://valkyrieinvest.com/brrr/

**Comment by dooberdoober** [comment]
BTCO - Invesco

Im not sure if the numbers listed as "Bid/Ask Prem/Disc" are what we want for this. Also, it lists two numbers🤷‍♂️

https://www.invesco.com/us/financial-products/etfs/product-detail?ticker=BTCO

**Comment by dooberdoober** [comment]
EZBC - Franklin Templeton

https://www.franklintempleton.com/investments/options/exchange-traded-funds/products/39639/SINGLCLASS/franklin-bitcoin-etf/EZBC

and then append "#view-historical-pricing" after EZBC >>...bitcoin-etf/EZBC#view-historical-pricing 
or find the graph towards the bottom of the linked page.

**Comment by dooberdoober** [comment]
HODL - VanEck

They have a "NAV & Premium/Discount History" XLS download @ https://www.vaneck.com/us/en/investments/bitcoin-trust-hodl/downloads/fundhistoprices/

Link to ETF details page @ https://www.vaneck.com/us/en/investments/bitcoin-trust-hodl/overview/

**Comment by JTuwiner** [comment]
We need the BTC per share. They don't have an API so can't really get the premium from the site itself.

**Comment by dooberdoober** [comment]
Understood. I was getting confused at how you were using some of the data sources mentioned here to get the proper data, especially given I didn't see any mention of an API with them.

Seemed kinda odd. Obviously I didn't think hard enough but instead thought I was helping add all the missing premium/discount data 😂🤦‍♂️

To ask a question I should have before making all those comments. We need to find data sources that are delivered via an API otherwise it's useless for the site? Or will something like the HODL xls doc work, assuming it includes a line for BTC/share within?

**Comment by JTuwiner** [comment]
No worries!

We're calcing BTC per share then doing math

This is for example how we calc BITB premium

((BITB.price * 1834.86) - marketPrice) / marketPrice) * 100

Where 1834.86 is the number of shares that would equal 1 BTC.

For premiums, we need the BTC per share. Since other than that, we get the ETF prices via an API and the Bitcoin price via an API.
