### ISSUE TITLE
real btc dominance

### ISSUE THREAD

**Issue by LodrikSatoshiar** [BitboBTC/Feedback#35]
Hi! I just subscribed to bitbo pro just to see btc real dominance graph, but I can't find it. Where is it in the website?
Thanks

**Comment by JTuwiner** [comment]
Hi, do you mean https://charts.bitbo.io/bitcoin-dominance/ or you want access to the TradingView indicator? 

To launch some new features we had to transition to a new server. As part of this we decided that real Bitcoin dominance was not worth our time to move, however the TradingView version is available. 

If you want TV version, use the form at https://charts.bitbo.io/indicators/ to submit your username

If you want the chart on site, I can commit to putting it back within 45 days, however only if you buy Bitbo Pro as otherwise it's not worth the time to get the API, and pay the developer to move the chart.

**Comment by LodrikSatoshiar** [comment]
The first link you sent is broken.
![image](https://github.com/user-attachments/assets/6d171c9f-8ef1-46a8-8e32-d101c97fc680)
In the past, I accesed this graph using bitcoindominance.com which now redirects to the same broken link.

I can't see any form in the link you sent to submit my username.
I already have an active Bitbo Pro subscription.

Thanks for your help.

**Comment by JTuwiner** [comment]
1. https://charts.bitbo.io/bitcoin-dominance/ yes this is broken because we did not move the chart over to new version of website

2. BitcoinDominance.com is owned by us, and we redirected it to the page on our site

3. if you send me your TradingView username here I can add you to TradingView version of Real Bitcoin Dominance Index as part of your trial (and let me know which email is your trial)

4. https://charts.bitbo.io/indicators/ you are right, there is a bug here. since you are trialing it is not showing the form. we are fixing it now

5. you are on a trial. if you pay for yearly membership we will put pack the Bitcoin Dominance chart on our site (unrelated to TV version).

thanks for the feedback!

**Comment by LodrikSatoshiar** [comment]
TV username: mike_clubs
email: miguel_klagges@hotmail.com

Thanks!

**Comment by JTuwiner** [comment]
Added you to all 15 Pro Indicators

Also added you to two bonus indicators, as a special welcome to Bitbo Pro and as a thank you for your feedback:
1. MMRP (One of only indicators to catch second top in 2021. it checks the 50-day MA vs the 50-day MA of the realized price, to track when the price is going up faster than coin movement)
2. realized price ratio (color-coded price vs realized price ratio) 

Thanks again for the feedback!

**Comment by LodrikSatoshiar** [comment]
I still see this when I click indicators, offering me to purchase bitbo pro again.
![image](https://github.com/user-attachments/assets/4aa6d06f-122f-4975-a708-448c3507f867)

Should I see TV indicators in your website? or those are accesible only through travingview website?

Thanks.

**Comment by JTuwiner** [comment]
Only thru the TV website.

for example if you search "Real Bitcoin" under the indicators tab youll now see this one in your account

<img width="665" alt="Screenshot 2024-08-05 at 3 49 00 PM" src="https://github.com/user-attachments/assets/3d5db63f-e171-4cee-b5f0-44a8d9f8c19d">

**Comment by LodrikSatoshiar** [comment]
Hey!
I just wanted to say thank you, and I'll pay for the yearly membership after trial period. I would like to check real btc dominance chart on your site in the future.
Thanks (:

**Comment by JTuwiner** [comment]
Okay, we will get to work on it once the payment goes thru!

May I ask why you like to use it?

I personally use it for something, but I'm just curious if others notice the same trends as me.

**Comment by LodrikSatoshiar** [comment]
I use it only for academic purposes. I don't care about price trends. I'm more interested in network trends, mining, and technology indicators.

**Comment by JTuwiner** [comment]
@AdiuvoInc your payment failed...like I said we'll build the chart on completion of yearly payment.

**Comment by LodrikSatoshiar** [comment]
That's odd, my card is working fine. I just tried again.

On the other hand, I love to pay with bitcoin (:

**Comment by JTuwiner** [comment]
Weird. We'll see if this one works!

we want to allow BTC but not able to yet. Stay tuned in 4-6 months :)

**Comment by JTuwiner** [comment]
<img width="932" alt="Screenshot 2024-08-22 at 2 20 23 PM" src="https://github.com/user-attachments/assets/9e200aea-1a8e-43be-979c-288c6358e5f8">

same error as last time. perhaps ask your bank what happened and then i can charge manually

**Comment by JTuwiner** [comment]
@AdiuvoInc

**Comment by JTuwiner** [comment]
@AdiuvoInc https://charts.bitbo.io/pricing/ 

we removed trials...so feel free to pay for yearly membership and you can see card errors. once we receive payment, we could start working on the dominance chart. 

Thanks!
